// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1Y3S7iVBdQmS493T2DjgzpkHS80QXv_E',
    appId: '1:3307252804:web:0225ea75d8d4003fe5e011',
    messagingSenderId: '3307252804',
    projectId: 'mon-premier-formulaire-e97f5',
    authDomain: 'mon-premier-formulaire-e97f5.firebaseapp.com',
    storageBucket: 'mon-premier-formulaire-e97f5.firebasestorage.app',
    measurementId: 'G-EXT77Y8MRF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRvpemLSIpHpBXpNuKEtCtUq9ZK84yzgI',
    appId: '1:3307252804:android:74e89ae914e8b57be5e011',
    messagingSenderId: '3307252804',
    projectId: 'mon-premier-formulaire-e97f5',
    storageBucket: 'mon-premier-formulaire-e97f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6BpX3L2mPwnwRO3xVoeLrbD9r6DsZ6hM',
    appId: '1:3307252804:ios:8ddebc1c52efec1ce5e011',
    messagingSenderId: '3307252804',
    projectId: 'mon-premier-formulaire-e97f5',
    storageBucket: 'mon-premier-formulaire-e97f5.firebasestorage.app',
    iosBundleId: 'com.example.appMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6BpX3L2mPwnwRO3xVoeLrbD9r6DsZ6hM',
    appId: '1:3307252804:ios:8ddebc1c52efec1ce5e011',
    messagingSenderId: '3307252804',
    projectId: 'mon-premier-formulaire-e97f5',
    storageBucket: 'mon-premier-formulaire-e97f5.firebasestorage.app',
    iosBundleId: 'com.example.appMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1Y3S7iVBdQmS493T2DjgzpkHS80QXv_E',
    appId: '1:3307252804:web:432f7b030cb773a8e5e011',
    messagingSenderId: '3307252804',
    projectId: 'mon-premier-formulaire-e97f5',
    authDomain: 'mon-premier-formulaire-e97f5.firebaseapp.com',
    storageBucket: 'mon-premier-formulaire-e97f5.firebasestorage.app',
    measurementId: 'G-36K2QDT6J7',
  );
}
